version: "3.9"

services:
  app:
    build: .
    ports:
      - 3333:3333
    depends_on:
      - db

    volumes:
      - .:/usr/app
  
  db:
    image: postgres
    restart: always
    tty: true
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    volumes:
      - pgdata:/data/postgres



volumes:
  pgdata:
    driver: local
